"""
web_research.py
----------------
Pluggable page-fetching layer for Scoutly's Company/Competitor research
agents. Mirrors llm_client.py's provider-abstraction pattern: a small ABC,
one real implementation, one deterministic mock for offline tests/demos.

This is what turns Scoutly's research agents from "reason about a URL from
general knowledge" into "summarize what's actually on the page" — the LLM
never sees a bare URL, it sees fetched, cleaned page text plus a list of
other pages it found along the way (leadership/press/careers/etc).

Also holds a free, no-API-key SEC EDGAR lookup for public 10-K filings,
since that's the one CAP 931 output requirement ("insight from public 10-K
reports") that isn't just "read a web page".
"""

from __future__ import annotations

import ipaddress
import re
import socket
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from urllib.parse import urljoin, urlparse

import requests
from bs4 import BeautifulSoup

_USER_AGENT = "Scoutly-Capstone/1.0 (educational prototype)"
_REQUEST_TIMEOUT = 8
_MAX_TEXT_CHARS = 6000
_LINK_KEYWORDS = (
    "about",
    "leadership",
    "team",
    "management",
    "press",
    "news",
    "investor",
    "careers",
    "jobs",
)


@dataclass
class PageContent:
    """Cleaned, size-capped result of fetching one URL."""

    url: str
    title: str = ""
    text: str = ""
    links: list[str] = field(default_factory=list)
    error: str | None = None


def _is_safe_url(url: str) -> bool:
    """
    Basic SSRF guard: this app fetches user-supplied URLs server-side, so it
    must not be usable to probe internal/private network addresses. Only
    http(s) with a hostname that resolves to a public IP is allowed.
    """
    parsed = urlparse(url)
    if parsed.scheme not in ("http", "https") or not parsed.hostname:
        return False
    try:
        infos = socket.getaddrinfo(parsed.hostname, None)
    except socket.gaierror:
        return False
    for info in infos:
        ip = ipaddress.ip_address(info[4][0])
        if ip.is_private or ip.is_loopback or ip.is_link_local or ip.is_reserved or ip.is_multicast:
            return False
    return True


def _parse_html(html: str, base_url: str) -> PageContent:
    """
    Pure function: HTML string -> PageContent. Kept separate from the actual
    HTTP call so it's unit-testable against fixture HTML with no network.
    """
    soup = BeautifulSoup(html, "html.parser")

    for tag in soup(["script", "style", "noscript"]):
        tag.decompose()

    title = soup.title.get_text(strip=True) if soup.title else ""
    text = " ".join(soup.get_text(separator=" ").split())[:_MAX_TEXT_CHARS]

    base_host = urlparse(base_url).netloc
    links: list[str] = []
    for anchor in soup.find_all("a", href=True):
        href = anchor["href"]
        label = anchor.get_text(strip=True).lower()
        haystack = f"{href.lower()} {label}"
        if not any(keyword in haystack for keyword in _LINK_KEYWORDS):
            continue
        absolute = urljoin(base_url, href)
        if urlparse(absolute).netloc != base_host:
            continue
        if absolute not in links:
            links.append(absolute)

    return PageContent(url=base_url, title=title, text=text, links=links)


class Fetcher(ABC):
    """Common interface every page-fetching backend must implement."""

    @abstractmethod
    def fetch_page(self, url: str) -> PageContent:
        """Return a PageContent for url. Must never raise for an ordinary
        network failure — set PageContent.error instead, so one bad URL
        doesn't crash the whole research run."""
        raise NotImplementedError


class HttpFetcher(Fetcher):
    """Real fetcher: GETs the URL and parses it with BeautifulSoup."""

    def fetch_page(self, url: str) -> PageContent:
        if not _is_safe_url(url):
            return PageContent(url=url, error="URL blocked (unsupported scheme or non-public host)")
        try:
            response = requests.get(
                url,
                headers={"User-Agent": _USER_AGENT},
                timeout=_REQUEST_TIMEOUT,
            )
            response.raise_for_status()
        except requests.RequestException as exc:
            return PageContent(url=url, error=f"fetch failed: {exc}")
        return _parse_html(response.text, url)


class MockFetcher(Fetcher):
    """Deterministic offline stand-in — same philosophy as llm_client.MockClient."""

    def fetch_page(self, url: str) -> PageContent:
        host = urlparse(url).netloc or url
        return PageContent(
            url=url,
            title=f"{host} — About Us",
            text=(
                f"{host} is a growing company in its industry. This is placeholder "
                "page text generated by MockFetcher (no network call was made) so the "
                "full pipeline can be exercised offline. Real deployments should set "
                "SCOUTLY_FETCH_MODE=http to fetch actual page content."
            ),
            links=[urljoin(url, "/about"), urljoin(url, "/leadership"), urljoin(url, "/press")],
        )


def get_fetcher(mode: str = "mock") -> Fetcher:
    """Factory: mode in {'http', 'mock'}."""
    mode = mode.lower()
    if mode == "http":
        return HttpFetcher()
    if mode == "mock":
        return MockFetcher()
    raise ValueError(f"Unknown fetch mode: {mode}")


# ---------- SEC EDGAR (public 10-K lookup, no API key required) ----------

# The legacy browse-edgar atom endpoint only returns entries for an exact
# single-CIK match, so a plain company-name search silently comes back
# empty. EDGAR's full text search JSON API matches on company name across
# actual filed documents and returns real accession numbers/dates/URLs.
_EDGAR_FULLTEXT_SEARCH_URL = "https://efts.sec.gov/LATEST/search-index"
_MAX_FILINGS = 5


@dataclass
class FilingInfo:
    company_name: str = ""
    form_type: str = ""
    filing_date: str = ""
    filing_url: str = ""


def _parse_edgar_search_json(data: dict) -> list[FilingInfo]:
    """Pure function: EDGAR full-text-search JSON -> list[FilingInfo], deduplicated
    by accession number. Unit-testable against a fixture dict."""
    filings: list[FilingInfo] = []
    seen_accessions: set[str] = set()

    for hit in data.get("hits", {}).get("hits", []):
        source = hit.get("_source", {})
        accession = source.get("adsh", "")
        if not accession or accession in seen_accessions:
            continue
        seen_accessions.add(accession)

        ciks = source.get("ciks") or []
        # EDGAR returns the CIK zero-padded to 10 digits (e.g. "0001327567"),
        # but the /Archives/ path below expects it without leading zeros.
        cik = ciks[0].lstrip("0") if ciks else ""
        accession_nodash = accession.replace("-", "")
        filing_url = (
            f"https://www.sec.gov/Archives/edgar/data/{cik}/{accession_nodash}/{accession}-index.htm"
            if cik
            else ""
        )
        display_names = source.get("display_names") or []
        filings.append(
            FilingInfo(
                company_name=display_names[0] if display_names else "",
                form_type=source.get("form", "10-K"),
                filing_date=source.get("file_date", ""),
                filing_url=filing_url,
            )
        )
    return filings


def lookup_public_filings(
    company_name: str, contact_email: str = "capstone-project@example.com"
) -> list[FilingInfo]:
    """
    Best-effort, free, no-key lookup of a company's recent 10-K filings on
    SEC EDGAR. Returns an empty list (not an error) for private companies or
    any lookup failure — "no public filings found" is a legitimate, expected
    result, not a bug.

    SEC's fair-access policy requires a descriptive User-Agent identifying
    the requester; contact_email should be overridden via
    SEC_EDGAR_CONTACT_EMAIL in production.
    """
    if not company_name:
        return []
    try:
        response = requests.get(
            _EDGAR_FULLTEXT_SEARCH_URL,
            params={"q": company_name, "forms": "10-K"},
            headers={"User-Agent": f"Scoutly-Capstone ({contact_email})"},
            timeout=_REQUEST_TIMEOUT,
        )
        response.raise_for_status()
        data = response.json()
    except (requests.RequestException, ValueError):
        return []
    return _parse_edgar_search_json(data)[:_MAX_FILINGS]


# ---------- Deeper 10-K analysis: real section text, not just metadata ----------

_FILING_SECTION_PATTERNS = {
    "risk_factors": r"Item\s+1A\.?\s*Risk\s*Factors",
    "mda": r"Item\s+7\.?\s*Management.?s\s*Discussion\s*and\s*Analysis",
    "cybersecurity": r"Item\s+1C\.?\s*Cybersecurity",
}
_NEXT_ITEM_HEADER = re.compile(r"\bItem\s+\d+[A-Z]?\.?", re.IGNORECASE)
_SECTION_EXCERPT_CHARS = 4000


def _find_primary_document_url(index_html: str, index_url: str) -> str | None:
    """
    Pure function: EDGAR filing-index HTML -> absolute URL of the primary
    filing document (not an exhibit). EDGAR wraps the primary document of
    an inline-XBRL filing in an "/ix?doc=..." viewer link, a reliable
    signal (verified live against a real Palo Alto Networks 10-K index
    page). Falls back to the first same-folder .htm document for older,
    pre-iXBRL filings.
    """
    match = re.search(r'/ix\?doc=([^"\s]+\.htm)', index_html, re.IGNORECASE)
    if match:
        return urljoin(index_url, match.group(1))

    soup = BeautifulSoup(index_html, "html.parser")
    folder = index_url.rsplit("/", 1)[0] + "/"
    for anchor in soup.find_all("a", href=True):
        href = anchor["href"]
        if not href.lower().endswith(".htm"):
            continue
        absolute = urljoin(index_url, href)
        if absolute.startswith(folder) and "index" not in absolute.lower():
            return absolute
    return None


def _extract_section(text: str, section_pattern: str) -> str:
    """
    Pure function: finds the LAST match of section_pattern in text — the
    first match in a 10-K is almost always its table of contents, not the
    actual section — and returns text up to the next "Item N" header or a
    length cap, whichever comes first. Returns "" if the pattern never
    matches, so a missing section reads as "not found," not fabricated.
    """
    matches = list(re.finditer(section_pattern, text, re.IGNORECASE))
    if not matches:
        return ""
    start = matches[-1].end()
    next_item = _NEXT_ITEM_HEADER.search(text, start)
    end = min(next_item.start() if next_item else len(text), start + _SECTION_EXCERPT_CHARS)
    return text[start:end].strip()


def fetch_filing_sections(
    filing_index_url: str, contact_email: str = "capstone-project@example.com"
) -> dict[str, str]:
    """
    Best-effort fetch of a 10-K's actual Risk Factors / MD&A / Cybersecurity
    section text (not just filing metadata), so the Company Research Agent
    can ground filing_highlights in real disclosure language. Returns empty
    strings (not an error) for any section it can't locate or fetch — same
    honesty pattern as lookup_public_filings: "not found" is a legitimate
    result, never a reason to invent content.
    """
    sections = dict.fromkeys(_FILING_SECTION_PATTERNS, "")
    if not filing_index_url:
        return sections

    headers = {"User-Agent": f"Scoutly-Capstone ({contact_email})"}
    try:
        index_response = requests.get(filing_index_url, headers=headers, timeout=_REQUEST_TIMEOUT)
        index_response.raise_for_status()
    except requests.RequestException:
        return sections

    document_url = _find_primary_document_url(index_response.text, filing_index_url)
    if not document_url:
        return sections
    try:
        doc_response = requests.get(document_url, headers=headers, timeout=_REQUEST_TIMEOUT)
        doc_response.raise_for_status()
    except requests.RequestException:
        return sections

    text = " ".join(BeautifulSoup(doc_response.text, "html.parser").get_text(separator=" ").split())
    return {name: _extract_section(text, pattern) for name, pattern in _FILING_SECTION_PATTERNS.items()}
